### PR TITLE
footer

### PR DESCRIPTION
**Pull request by KrunalGupta02**
Add a footer for news app website

### CODE REVIEW

**Comment by abhishekgit03** [comment]
@KrunalGupta02 Please reduce the height of the footer. Its too big. Push the code after making changes.

**Comment by KrunalGupta02** [comment]
Ok

**Comment by KrunalGupta02** [comment]
@abhishekgit03 can u now check the height of footer

**Comment by KrunalGupta02** [comment]
Hi @abhishekgit03, can u plz tell me why this **### _merge_**  is not participating showing in my hacktoberfest account

**Comment by abhishekgit03** [comment]
It takes 15-20 mins to get reflected on Hacktoberfest Page.

**Comment by abhishekgit03** [comment]
Please send me the screenshot on "abhishek20dgp@gmail.com"

**Pull request merged**
